### ISSUE TITLE
Remove `master` branch and keep only cypress and baobab branches

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl-helm-charts#197]

**Comment by jay-kim-kor** [comment]
> @jay-kim-kor Yes, my bad. It should have been opened up in `orakl-helm-charts`. I am not sure it is possible to transfer issue between repositories. If not, let's close this one and open new one in `orakl-helm-charts`.

Don't worry. I transferred it. 👍🏼

**Comment by jay-kim-kor** [comment]
We decided to unify both branches into main.
