### ISSUE TITLE
Remove deprecated `LOG_DIR`

### ISSUE THREAD

**Issue by jay-bisonai** [Bisonai/orakl-helm-charts#21]

**Comment by jay-bisonai** [comment]
It's added from wrong cherry-pick and not merged to baobab/cypress branch. so, we don't have any `LOG_DIR`.

**Comment by martinkersner** [comment]
@jay-bisonai What about this? https://github.com/search?q=repo%3ABisonai%2Forakl-helm-charts%20LOG_DIR&type=code 🤔

**Comment by jay-bisonai** [comment]
@martinkersner In `main` branch, `LOG_DIR` can be still used by node operator. it's public part.
and the reason why we deleted `LOG_DIR` is reduce our infra cost. so, this is only apply our infra code(`gcp-baobab/cypress-prod`)
